// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered tool to generate curated collections of products based on trends or user preferences.
 *
 * - generateCuratedCollections - A function that handles the generation of curated collections.
 * - GenerateCuratedCollectionsInput - The input type for the generateCuratedCollections function.
 * - GenerateCuratedCollectionsOutput - The return type for the generateCuratedCollections function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCuratedCollectionsInputSchema = z.object({
  trend: z.string().describe('The current trend to base the collection on.'),
  userPreferences: z.string().describe('The user preferences to tailor the collection to.'),
});
export type GenerateCuratedCollectionsInput = z.infer<
  typeof GenerateCuratedCollectionsInputSchema
>;

const GenerateCuratedCollectionsOutputSchema = z.object({
  collectionName: z.string().describe('The name of the curated collection.'),
  productIds: z
    .array(z.string())
    .describe('The IDs of the products included in the collection.'),
  description: z.string().describe('A description of the curated collection.'),
});
export type GenerateCuratedCollectionsOutput = z.infer<
  typeof GenerateCuratedCollectionsOutputSchema
>;

export async function generateCuratedCollections(
  input: GenerateCuratedCollectionsInput
): Promise<GenerateCuratedCollectionsOutput> {
  return generateCuratedCollectionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCuratedCollectionsPrompt',
  input: {schema: GenerateCuratedCollectionsInputSchema},
  output: {schema: GenerateCuratedCollectionsOutputSchema},
  prompt: `You are an expert curator, skilled at creating product collections based on trends and user preferences.

  Based on the following trend: {{trend}}
  And the following user preferences: {{userPreferences}}
  Create a curated collection of products.

  Return the name of the collection, a list of product IDs to include, and a description of the collection.
  `,
});

const generateCuratedCollectionsFlow = ai.defineFlow(
  {
    name: 'generateCuratedCollectionsFlow',
    inputSchema: GenerateCuratedCollectionsInputSchema,
    outputSchema: GenerateCuratedCollectionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
