// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  "projectId": "studio-3065937203-974ad",
  "appId": "1:107532653166:web:bf2c9ad52b686827390c7f",
  "storageBucket": "studio-3065937203-974ad.firebasestorage.app",
  "apiKey": "AIzaSyASJneCXIeIgL598P_KpkLBG9NTggAHMgc",
  "authDomain": "studio-3065937203-974ad.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "107532653166"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);

export { app, auth };
