import { SiteHeader } from '@/components/common/site-header';
import { SiteFooter } from '@/components/common/site-footer';
import { PageHeader } from '@/components/common/page-header';
import { generateCuratedCollectionAction } from '../actions';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ProductCard } from '@/components/product-card';
import { Label } from '@/components/ui/label';

export default async function CollectionsPage({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  const trend = (searchParams.trend as string) || '';
  let collection;
  if (trend) {
    collection = await generateCuratedCollectionAction({ trend });
  }

  return (
    <>
      <SiteHeader />
      <main className="flex-1">
        <div className="container mx-auto px-4 md:px-6 py-12 md:py-16">
          <PageHeader
            title="Curated Collections"
            description="Discover unique collections generated by AI, based on your inspiration."
          />
          <Card className="mb-12">
            <CardHeader>
              <CardTitle>Create Your Own Collection</CardTitle>
              <CardDescription>
                Enter a theme, trend, or idea, and let our AI build a collection for you. Try &quot;Cozy Autumn Morning&quot; or &quot;Coastal Grandmother&quot;.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form className="flex flex-col sm:flex-row items-end gap-4">
                <div className="grid w-full gap-1.5">
                  <Label htmlFor="trend">Theme or Trend</Label>
                  <Input
                    id="trend"
                    name="trend"
                    placeholder="e.g., Forest Cabin Retreat"
                    defaultValue={trend}
                  />
                </div>
                <Button type="submit">Generate Collection</Button>
              </form>
            </CardContent>
          </Card>
          
          {collection && (
            <section>
              <Card className="bg-card/50">
                <CardHeader>
                  <CardTitle className="text-3xl font-headline">{collection.collectionName}</CardTitle>
                  <CardDescription>{collection.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                    {collection.products.map(product => (
                      <ProductCard key={product.id} product={product} />
                    ))}
                  </div>
                </CardContent>
              </Card>
            </section>
          )}

           {!collection && !trend && (
             <div className="text-center py-16 border-2 border-dashed rounded-lg">
                <p className="text-muted-foreground">Enter a theme above to generate your first collection.</p>
             </div>
           )}

        </div>
      </main>
      <SiteFooter />
    </>
  );
}
